apiVersion: v1
kind: Namespace
metadata:
  name: store-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iphone-deployment
  namespace: store-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iphone
  template:
    metadata:
      labels:
        app: iphone
    spec:
      containers:
        - name: iphone-container
          image: harishnshetty/iphone:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: iphone-service
  namespace: store-ns
spec:
  selector:
    app: iphone
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP

